### ISSUE TITLE
ModuleNotFoundError: No module named '_hub'

### ISSUE THREAD

**Issue by alexisbronchart** [db0/AI-Horde-Worker#191]
I've successfully ran the update-runtime script but when I run the `horde-alchemist_bridge` script I'm getting this error:
```
.\horde-alchemist_bridge.cmd
INIT       | OS Default  | Ray temp dir'
Traceback (most recent call last):
  File "...\stable-horde-worker\bridge_alchemy.py", line 15, in <module>
    model_manager = ModelManager(
  File "...\stable-horde-worker\conda\envs\windows\lib\site-packages\nataili\model_manager\super.py", line 52, in __init__
    from nataili.model_manager.blip import BlipModelManager
  File "...\stable-horde-worker\conda\envs\windows\lib\site-packages\nataili\model_manager\blip.py", line 32, in <module>
    from nataili.util.blip import blip_decoder
  File "...\stable-horde-worker\conda\envs\windows\lib\site-packages\nataili\util\blip\__init__.py", line 1, in <module>
    from .blip import blip_decoder
  File "...\stable-horde-worker\conda\envs\windows\lib\site-packages\nataili\util\blip\blip.py", line 13, in <module>
    from timm.models.hub import download_cached_file
  File "...\stable-horde-worker\conda\envs\windows\lib\site-packages\timm\models\hub.py", line 1, in <module>
    from _hub import *
ModuleNotFoundError: No module named '_hub'
```

**Comment by db0** [comment]
can you run `update-runtime.cmd --hordelib` and try again?

**Comment by jug-dev** [comment]
Thanks for the report. This was fixed shortly after. As db0 says simply update and all will be well.

**Comment by alexisbronchart** [comment]
> can you run `update-runtime.cmd --hordelib` and try again?

Just tried it and still the same error. I also tried cloning the repo again in a clean directory: same.
